name: cs7641_1
channels:
  - districtdatalabs
  - defaults
dependencies:
  - atomicwrites
  - attrs=18.2.0
  - backcall=0.1.0
  - backports=1.0
  - backports.os
  - blas=1.0=mkl
  - bleach=3.1.0
  - ca-certificates=2018.12.5
  - cairo=1.14.12
  - certifi=2018.11.29
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.3.0
  - defusedxml=0.5.0
  - entrypoints=0.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - fribidi=1.0.5
  - gettext=0.19.8.1
  - glib=2.56.2
  - graphite2=1.3.13
  - graphviz=2.40.1
  - harfbuzz=1.8.8
  - html5lib=1.0.1
  - icu=58.2
  - importlib_metadata=0.7
  - intel-openmp=2019.1=144
  - ipykernel=5.1.0
  - ipython=7.2.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - jedi=0.13.2
  - jinja2=2.10
  - jpeg=9b
  - jsonschema=2.6.0
  - kiwisolver=1.0.1
  # - libcxx
  # - libcxxabi
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran
  - libiconv=1.15
  - libpng=1.6.36
  - libsodium=1.0.16
  - libtiff=4.0.10
  - libxml2=2.9.9
  - markupsafe=1.1.0
  - matplotlib=2.2.3
  - mistune=0.8.4
  - mkl=2019.1=144
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - more-itertools=5.0.0
  - nbconvert=5.4.0
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=5.7.4
  - numpy=1.15.4
  - numpy-base=1.15.4
  - openssl=1.1.1a
  - pandas=0.24.0
  - pandoc=1.19.2.1
  - pandocfilters=1.4.2
  - pango=1.42.4
  - parso=0.3.1
  - path.py=11.5.0
  - pcre=8.42
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pip=18.1
  - pixman=0.36.0
  - pluggy=0.8.1
  - prometheus_client=0.5.0
  - prompt_toolkit=2.0.7
  - ptyprocess=0.6.0
  - py=1.7.0
  - pygments=2.3.1
  - pyparsing=2.3.1
  - pyqt=5.9.2
  - pytest=4.1.1
  - pytest-runner=4.2
  - python=3.6.8
  - python-dateutil=2.7.5
  - python-graphviz=0.8.4
  - pytz=2018.9
  - pyzmq=17.1.2
  - qt=5.9.7
  - qtconsole=4.4.3
  - readline=7.0
  - scikit-learn=0.20.2
  - scipy=1.2.0
  - send2trash=1.5.0
  - setuptools=40.6.3
  - simplegeneric=0.8.1
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.26.0
  - terminado=0.8.1
  - testpath=0.4.2
  - tk=8.6.8
  - tornado=5.1.1
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.32.3
  - widgetsnbextension=3.4.2
  - xz=5.2.4
  - yellowbrick=0.9
  - zeromq=4.2.5
  - zlib=1.2.11
  - zstd=1.3.7

